2018-02-26 15:33:02,358 INFO     <type 'unicode'>
2018-02-26 15:33:02,359 INFO     D:/00 eigene Daten/000 FH/S 6/Segway/SegwayControllerCode/testInertialSensor/duda.mRay
2018-02-28 12:00:00,005 INFO     starting application
2018-02-28 12:00:10,394 INFO     GUI load complete
2018-04-30 20:15:58,211 INFO     starting application
2018-04-30 20:15:58,539 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 15, in <module>
    from core.hardwareInterfaces import UdpInterface, UsbHidInterface, SerialInterface
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\hardwareInterfaces.py", line 6, in <module>
    import serial
ImportError: No module named serial

2018-04-30 20:16:24,908 INFO     starting application
2018-04-30 20:16:25,017 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 15, in <module>
    from core.hardwareInterfaces import UdpInterface, UsbHidInterface, SerialInterface
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\hardwareInterfaces.py", line 6, in <module>
    import serial
ImportError: No module named serial

2018-04-30 20:19:06,532 INFO     starting application
2018-04-30 20:19:10,279 INFO     GUI load complete
2018-04-30 20:19:51,796 INFO     starting application
2018-04-30 20:19:52,822 INFO     GUI load complete
2018-04-30 20:21:06,122 INFO     <class 'PyQt4.QtCore.QString'>
2018-04-30 20:21:06,122 INFO     <type 'unicode'>
2018-04-30 20:21:06,122 INFO     D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microcontrollerTestProjects/arduinoSerial/testArduinoSerial.mRay
2018-04-30 20:53:38,092 INFO     starting application
2018-04-30 20:53:43,230 INFO     GUI load complete
2018-04-30 20:58:43,661 INFO     starting application
2018-04-30 20:58:44,500 INFO     GUI load complete
2018-04-30 21:08:56,236 INFO     starting application
2018-04-30 21:08:56,901 INFO     GUI load complete
2018-04-30 21:19:24,749 INFO     starting application
2018-04-30 21:19:25,398 INFO     GUI load complete
2018-04-30 21:24:31,819 INFO     starting application
2018-04-30 21:24:32,446 INFO     GUI load complete
2018-04-30 21:31:26,874 INFO     starting application
2018-04-30 21:31:27,677 INFO     GUI load complete
2018-04-30 21:31:46,176 INFO     starting application
2018-04-30 21:31:46,763 INFO     GUI load complete
2018-04-30 21:31:48,091 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 116, in mousePressEvent
    if QMouseEvent.Button() == QtCore.Qt.LeftButton:
AttributeError: 'QMouseEvent' object has no attribute 'Button'

2018-04-30 21:31:48,092 ERROR    uncaught exception
2018-04-30 21:31:48,094 ERROR    
2018-04-30 21:32:35,299 INFO     starting application
2018-04-30 21:32:35,990 INFO     GUI load complete
2018-04-30 21:32:37,578 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 120, in mousePressEvent
    menu = QtGui.QMenu.contextMenu("Context menu", self)
AttributeError: type object 'QMenu' has no attribute 'contextMenu'

2018-04-30 21:32:37,579 ERROR    uncaught exception
2018-04-30 21:32:37,581 ERROR    
2018-04-30 21:34:01,473 INFO     starting application
2018-04-30 21:34:02,158 INFO     GUI load complete
2018-04-30 21:39:37,660 INFO     starting application
2018-04-30 21:39:38,529 INFO     GUI load complete
2018-04-30 21:39:48,026 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-04-30 21:39:48,029 ERROR    uncaught exception
2018-04-30 21:39:48,029 ERROR    
2018-04-30 21:43:25,832 INFO     starting application
2018-04-30 21:43:26,556 INFO     GUI load complete
2018-04-30 21:43:59,943 INFO     starting application
2018-04-30 21:44:00,592 INFO     GUI load complete
2018-04-30 21:45:05,644 INFO     starting application
2018-04-30 21:45:06,286 INFO     GUI load complete
2018-04-30 21:45:29,536 INFO     starting application
2018-04-30 21:45:30,236 INFO     GUI load complete
2018-04-30 21:49:27,112 INFO     starting application
2018-04-30 21:49:27,769 INFO     GUI load complete
2018-04-30 21:49:57,364 INFO     starting application
2018-04-30 21:49:58,092 INFO     GUI load complete
2018-04-30 21:54:17,976 INFO     starting application
2018-04-30 21:54:18,178 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 33, in <module>
    from gui.tabWaterLineExperiment import TabWaterLineExperiment
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabWaterLineExperiment.py", line 8, in <module>
    from gui.plotWidget import PlotWidget
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\plotWidget.py", line 419
    self.channelControllers[channel.id]["controllerBox"].
                                                        ^
SyntaxError: invalid syntax

2018-04-30 21:54:35,414 INFO     starting application
2018-04-30 21:54:35,553 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 33, in <module>
    from gui.tabWaterLineExperiment import TabWaterLineExperiment
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabWaterLineExperiment.py", line 8, in <module>
    from gui.plotWidget import PlotWidget
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\plotWidget.py", line 419
    self.channelControllers[channel.id]["controllerBox"].
                                                        ^
SyntaxError: invalid syntax

2018-04-30 21:54:39,273 INFO     starting application
2018-04-30 21:54:39,428 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 33, in <module>
    from gui.tabWaterLineExperiment import TabWaterLineExperiment
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabWaterLineExperiment.py", line 8, in <module>
    from gui.plotWidget import PlotWidget
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\plotWidget.py", line 419
    self.channelControllers[channel.id]["controllerBox"].
                                                        ^
SyntaxError: invalid syntax

2018-04-30 21:54:47,039 INFO     starting application
2018-04-30 21:54:47,164 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 33, in <module>
    from gui.tabWaterLineExperiment import TabWaterLineExperiment
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabWaterLineExperiment.py", line 8, in <module>
    from gui.plotWidget import PlotWidget
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\plotWidget.py", line 419
    self.channelControllers[channel.id]["controllerBox"].
                                                        ^
SyntaxError: invalid syntax

2018-04-30 21:55:43,632 INFO     starting application
2018-04-30 21:55:44,292 INFO     GUI load complete
2018-04-30 21:55:54,638 INFO     starting application
2018-04-30 21:55:55,240 INFO     GUI load complete
2018-04-30 21:56:00,576 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 138, in changeChannelColor
    self.colorBox.brush = QtGui.QBrush(QtGui.QPen(color.red(), color.green(), color.blue()))
TypeError: arguments did not match any overloaded call:
  QPen(): too many arguments
  QPen(Qt.PenStyle): too many arguments
  QPen(QColor): argument 1 has unexpected type 'int'
  QPen(QBrush, float, style: Qt.PenStyle = Qt.SolidLine, cap: Qt.PenCapStyle = Qt.SquareCap, join: Qt.PenJoinStyle = Qt.BevelJoin): argument 1 has unexpected type 'int'
  QPen(QPen): argument 1 has unexpected type 'int'
  QPen(QVariant): too many arguments

2018-04-30 21:56:00,581 ERROR    uncaught exception
2018-04-30 21:56:00,582 ERROR    
2018-04-30 21:56:18,818 INFO     starting application
2018-04-30 21:56:19,513 INFO     GUI load complete
2018-04-30 21:56:23,336 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 138, in changeChannelColor
    self.colorBox.brush = QtGui.QBrush(QtGui.QPen(colorTuple))
TypeError: QPen(): argument 1 has unexpected type 'tuple'

2018-04-30 21:56:23,338 ERROR    uncaught exception
2018-04-30 21:56:23,338 ERROR    
2018-04-30 21:56:49,431 INFO     starting application
2018-04-30 21:56:50,082 INFO     GUI load complete
2018-04-30 21:56:55,392 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 138, in changeChannelColor
    self.colorBox.brush = QtGui.QBrush(QtGui.QPen(QtGui.QColor(colorTuple)))
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'tuple'
  QColor(int): too many arguments
  QColor(QVariant): argument 1 has unexpected type 'tuple'
  QColor(): argument 1 has unexpected type 'tuple'
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'tuple'

2018-04-30 21:56:55,397 ERROR    uncaught exception
2018-04-30 21:56:55,398 ERROR    
2018-04-30 21:57:13,223 INFO     starting application
2018-04-30 21:57:13,858 INFO     GUI load complete
2018-04-30 21:57:19,282 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 138, in changeChannelColor
    self.colorBox.brush = QtGui.QBrush(QtGui.QPen(color))
TypeError: QBrush(): argument 1 has unexpected type 'QPen'

2018-04-30 21:57:19,283 ERROR    uncaught exception
2018-04-30 21:57:19,283 ERROR    
2018-04-30 21:57:33,723 INFO     starting application
2018-04-30 21:57:34,316 INFO     GUI load complete
2018-04-30 21:59:58,285 INFO     starting application
2018-04-30 21:59:58,888 INFO     GUI load complete
2018-04-30 22:01:16,785 INFO     starting application
2018-04-30 22:01:17,467 INFO     GUI load complete
2018-05-01 19:35:52,345 INFO     starting application
2018-05-01 19:35:53,286 INFO     GUI load complete
2018-05-01 19:36:23,815 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 687, in save
    self.projectConfigManager.save(self.projectSettings, self.channels, self.commands)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 41, in save
    commandDict["displayScaleFactor"] = list(command._displayScaleFactor)
TypeError: 'float' object is not iterable

2018-05-01 19:36:23,818 ERROR    uncaught exception
2018-05-01 19:36:23,819 ERROR    
2018-05-01 19:36:58,946 INFO     starting application
2018-05-01 19:36:59,539 INFO     GUI load complete
2018-05-01 19:46:59,496 INFO     starting application
2018-05-01 19:47:00,240 INFO     GUI load complete
2018-05-01 19:47:13,401 INFO     starting application
2018-05-01 19:47:14,013 INFO     GUI load complete
2018-05-01 19:48:52,193 INFO     starting application
2018-05-01 19:48:52,809 INFO     GUI load complete
2018-05-01 19:50:01,318 INFO     starting application
2018-05-01 19:50:01,971 INFO     GUI load complete
2018-05-01 19:50:14,947 INFO     starting application
2018-05-01 19:50:15,555 INFO     GUI load complete
2018-05-01 19:51:04,348 INFO     starting application
2018-05-01 19:51:04,954 INFO     GUI load complete
2018-05-01 19:52:50,303 INFO     starting application
2018-05-01 19:52:50,917 INFO     GUI load complete
2018-05-01 20:00:03,328 INFO     starting application
2018-05-01 20:00:03,832 INFO     GUI load complete
2018-05-01 20:00:37,427 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 624, in openRecent
    self.loadProject(recentPath)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 632, in loadProject
    self.projectSettings, self.channels, self.commands, self.messageFormatList, self.communicator = self.projectConfigManager.buildModelFromConfigFile(pathToProjectFile)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 113, in buildModelFromConfigFile
    jsonStuff = self.open(pathToConfigFile)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 98, in open
    return json.loads(content)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 40 column 9 (char 916)

2018-05-01 20:00:37,443 ERROR    
2018-05-01 20:01:21,259 INFO     starting application
2018-05-01 20:01:21,836 INFO     GUI load complete
2018-05-01 20:02:25,171 INFO     starting application
2018-05-01 20:02:25,877 INFO     GUI load complete
2018-05-01 20:58:17,582 INFO     starting application
2018-05-01 20:58:18,822 INFO     GUI load complete
2018-05-01 20:58:43,630 INFO     starting application
2018-05-01 20:58:44,219 INFO     GUI load complete
2018-05-01 20:58:59,427 INFO     starting application
2018-05-01 20:59:00,038 INFO     GUI load complete
2018-05-01 21:00:39,529 INFO     starting application
2018-05-01 21:00:40,153 INFO     GUI load complete
2018-05-01 21:00:54,849 INFO     starting application
2018-05-01 21:00:55,474 INFO     GUI load complete
2018-05-01 21:01:10,506 INFO     starting application
2018-05-01 21:01:11,130 INFO     GUI load complete
2018-05-01 21:01:13,415 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\commandWidgets\smallGenericCommand.py", line 202, in showHistory
    listWidget = QtGui.QListWidget(self)
TypeError: QListWidget(parent: QWidget = None): argument 1 has unexpected type 'SmallGenericCommand'

2018-05-01 21:01:13,417 ERROR    uncaught exception
2018-05-01 21:01:13,418 ERROR    
2018-05-01 21:01:31,286 INFO     starting application
2018-05-01 21:01:32,076 INFO     GUI load complete
2018-05-01 21:03:11,035 INFO     starting application
2018-05-01 21:03:11,789 INFO     GUI load complete
2018-05-01 21:03:47,950 INFO     starting application
2018-05-01 21:03:48,591 INFO     GUI load complete
2018-05-01 21:04:15,632 INFO     starting application
2018-05-01 21:04:16,214 INFO     GUI load complete
2018-05-01 21:04:41,693 INFO     starting application
2018-05-01 21:04:42,301 INFO     GUI load complete
2018-05-01 21:04:55,380 INFO     starting application
2018-05-01 21:04:55,948 INFO     GUI load complete
2018-05-01 21:06:08,911 INFO     starting application
2018-05-01 21:06:09,509 INFO     GUI load complete
2018-05-01 21:06:11,200 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\commandWidgets\smallGenericCommand.py", line 208, in showHistory
    listWidget.addItem(aValueString)
TypeError: arguments did not match any overloaded call:
  addItem(self, QListWidgetItem): argument 1 has unexpected type 'float'
  addItem(self, QString): argument 1 has unexpected type 'float'

2018-05-01 21:06:11,203 ERROR    uncaught exception
2018-05-01 21:06:11,203 ERROR    
2018-05-01 21:06:23,918 INFO     starting application
2018-05-01 21:06:24,522 INFO     GUI load complete
2018-05-01 21:23:36,525 INFO     starting application
2018-05-01 21:23:37,092 INFO     GUI load complete
2018-05-01 21:23:42,405 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 624, in openRecent
    self.loadProject(recentPath)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 644, in loadProject
    self.addTabs(self.projectSettings.tabSettingsDescriptions)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 301, in addTabs
    self.addOnlyOneWidget(tabs)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 420, in addOnlyOneWidget
    self.serialMonitor)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabSmallGenericView.py", line 34, in __init__
    self.controller = ControllerSmallGeneric(self.commands, self.channels)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\controllerSmallGeneric.py", line 42, in __init__
    self.initItems()
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\controllerSmallGeneric.py", line 52, in initItems
    commandItem = SmallGenericCommand(command)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\commandWidgets\smallGenericCommand.py", line 53, in __init__
    self.historyListWidget = ListWidgetSpecial(self)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\listWidgetSpecial.py", line 11, in __init__
    super(ListWidgetSpecial, self).__init__(parent)
TypeError: QListWidget(parent: QWidget = None): argument 1 has unexpected type 'SmallGenericCommand'

2018-05-01 21:23:42,427 ERROR    
2018-05-01 21:23:59,306 INFO     starting application
2018-05-01 21:23:59,959 INFO     GUI load complete
2018-05-01 21:24:44,424 INFO     starting application
2018-05-01 21:24:45,051 INFO     GUI load complete
2018-05-01 21:25:10,828 INFO     starting application
2018-05-01 21:25:11,418 INFO     GUI load complete
2018-05-01 21:25:24,707 INFO     starting application
2018-05-01 21:25:25,315 INFO     GUI load complete
2018-05-01 21:29:05,687 INFO     starting application
2018-05-01 21:29:06,522 INFO     GUI load complete
2018-05-01 21:29:49,188 INFO     starting application
2018-05-01 21:29:49,884 INFO     GUI load complete
2018-05-01 21:31:10,844 INFO     starting application
2018-05-01 21:31:11,500 INFO     GUI load complete
2018-05-01 21:31:16,032 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\listWidgetSpecial.py", line 22, in keyPressEvent
    self.valueSelected.emit()
TypeError: ListWidgetSpecial.valueSelected[float] signal has 1 argument(s) but 0 provided

2018-05-01 21:31:16,032 ERROR    uncaught exception
2018-05-01 21:31:16,033 ERROR    
2018-05-01 21:31:35,549 INFO     starting application
2018-05-01 21:31:36,138 INFO     GUI load complete
2018-05-01 21:31:40,025 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\listWidgetSpecial.py", line 22, in keyPressEvent
    self.valueSelected.emit(self.itemAt(self.currentIndex()))
TypeError: arguments did not match any overloaded call:
  itemAt(self, QPoint): argument 1 has unexpected type 'QModelIndex'
  itemAt(self, int, int): argument 1 has unexpected type 'QModelIndex'

2018-05-01 21:31:40,026 ERROR    uncaught exception
2018-05-01 21:31:40,028 ERROR    
2018-05-01 21:33:23,815 INFO     starting application
2018-05-01 21:33:24,407 INFO     GUI load complete
2018-05-01 21:33:28,880 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\listWidgetSpecial.py", line 22, in keyPressEvent
    self.valueSelected.emit(self.currentItem().text())
TypeError: ListWidgetSpecial.valueSelected[float].emit(): argument 1 has unexpected type 'QString'

2018-05-01 21:33:28,881 ERROR    uncaught exception
2018-05-01 21:33:28,881 ERROR    
2018-05-01 21:34:08,114 INFO     starting application
2018-05-01 21:34:08,730 INFO     GUI load complete
2018-05-01 21:34:41,207 INFO     starting application
2018-05-01 21:34:41,822 INFO     GUI load complete
2018-05-01 21:35:33,321 INFO     starting application
2018-05-01 21:35:34,069 INFO     GUI load complete
2018-05-01 21:36:01,269 INFO     starting application
2018-05-01 21:36:01,888 INFO     GUI load complete
2018-05-01 21:36:03,865 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\graphicItems\commandWidgets\smallGenericCommand.py", line 217, in showHistory
    self.historyListWidget.setCurrentIndex(0)
TypeError: setCurrentIndex(self, QModelIndex): argument 1 has unexpected type 'int'

2018-05-01 21:36:03,867 ERROR    uncaught exception
2018-05-01 21:36:03,867 ERROR    
2018-05-01 21:36:54,829 INFO     starting application
2018-05-01 21:36:55,440 INFO     GUI load complete
2018-05-01 21:37:31,223 INFO     starting application
2018-05-01 21:37:31,858 INFO     GUI load complete
2018-05-01 21:40:20,247 INFO     starting application
2018-05-01 21:40:20,864 INFO     GUI load complete
2018-05-01 21:45:29,721 INFO     starting application
2018-05-01 21:45:30,341 INFO     GUI load complete
2018-05-01 21:45:46,410 INFO     starting application
2018-05-01 21:45:47,049 INFO     GUI load complete
2018-05-01 21:46:21,049 INFO     starting application
2018-05-01 21:46:21,680 INFO     GUI load complete
2018-05-01 21:46:33,848 INFO     starting application
2018-05-01 21:46:34,701 INFO     GUI load complete
2018-05-01 21:48:12,707 INFO     starting application
2018-05-01 21:48:13,325 INFO     GUI load complete
2018-05-01 21:51:33,316 INFO     starting application
2018-05-01 21:51:34,114 INFO     GUI load complete
2018-05-02 21:02:19,868 INFO     starting application
2018-05-02 21:02:21,104 INFO     GUI load complete
2018-05-02 21:03:04,924 INFO     starting application
2018-05-02 21:03:05,565 INFO     GUI load complete
2018-05-02 21:06:26,000 INFO     starting application
2018-05-02 21:06:26,911 INFO     GUI load complete
2018-05-02 21:06:39,921 INFO     starting application
2018-05-02 21:07:29,533 INFO     starting application
2018-05-02 21:07:30,200 INFO     GUI load complete
2018-05-02 21:09:14,266 INFO     starting application
2018-05-02 21:09:14,950 INFO     GUI load complete
2018-05-02 21:09:56,641 INFO     starting application
2018-05-02 21:09:57,078 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 33, in <module>
    from gui.tabWaterLineExperiment import TabWaterLineExperiment
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabWaterLineExperiment.py", line 8, in <module>
    from gui.plotWidget import PlotWidget
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\plotWidget.py", line 6, in <module>
    from gui.idCheckBox import IdColorLabelCheckbox
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 6, in <module>
    class IdColorLabelCheckbox(QtGui.QWidget):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 96, in IdColorLabelCheckbox
    @QtCore.pyqtSignal(object)
TypeError: native Qt signal is not callable

2018-05-02 21:10:02,812 INFO     starting application
2018-05-02 21:10:03,125 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 136, in <module>
    run()
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 130, in run
    app = MicroRay(sys.argv, exceptionMagnet)
  File "D:/00 eigene Daten/000 FH/S 4/Regelungstechnik/Regelungsversuch/microRay/microRay.py", line 98, in __init__
    from gui.mainWindow import MicroRayMainWindow
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 33, in <module>
    from gui.tabWaterLineExperiment import TabWaterLineExperiment
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\tabWaterLineExperiment.py", line 8, in <module>
    from gui.plotWidget import PlotWidget
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\plotWidget.py", line 6, in <module>
    from gui.idCheckBox import IdColorLabelCheckbox
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 6, in <module>
    class IdColorLabelCheckbox(QtGui.QWidget):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 96, in IdColorLabelCheckbox
    @QtCore.pyqtSignal()
TypeError: native Qt signal is not callable

2018-05-02 21:10:20,173 INFO     starting application
2018-05-02 21:10:20,749 INFO     GUI load complete
2018-05-02 21:10:48,296 INFO     starting application
2018-05-02 21:10:48,983 INFO     GUI load complete
2018-05-02 21:11:41,207 INFO     starting application
2018-05-02 21:11:41,819 INFO     GUI load complete
2018-05-07 19:19:14,704 INFO     starting application
2018-05-07 19:19:16,704 INFO     GUI load complete
2018-05-07 20:36:06,066 INFO     starting application
2018-05-07 20:36:11,999 INFO     GUI load complete
2018-05-07 20:40:20,733 INFO     starting application
2018-05-07 20:40:21,592 INFO     GUI load complete
2018-05-07 20:40:25,016 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 18, in updateSettings
    dialog.lineEditVariableName.setText(channel.name)
AttributeError: 'SingleChannelSettingsConfig' object has no attribute 'lineEditVariableName'

2018-05-07 20:40:25,017 ERROR    uncaught exception
2018-05-07 20:40:25,019 ERROR    
2018-05-07 20:41:08,796 INFO     starting application
2018-05-07 20:41:09,467 INFO     GUI load complete
2018-05-07 20:41:11,599 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 18, in updateSettings
    dialog.lineEditVariableName.setText(channel.name)
AttributeError: 'SingleChannelSettingsConfig' object has no attribute 'lineEditVariableName'

2018-05-07 20:41:11,601 ERROR    uncaught exception
2018-05-07 20:41:11,601 ERROR    
2018-05-07 20:43:20,546 INFO     starting application
2018-05-07 20:43:21,257 INFO     GUI load complete
2018-05-07 20:43:28,473 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 27, in updateSettings
    palette.setColor(QtCore.Qt.BackgroundRole, color)
TypeError: arguments did not match any overloaded call:
  setColor(self, QPalette.ColorGroup, QPalette.ColorRole, QColor): first argument of unbound method must have type 'QPalette'
  setColor(self, QPalette.ColorRole, QColor): first argument of unbound method must have type 'QPalette'

2018-05-07 20:43:28,474 ERROR    uncaught exception
2018-05-07 20:43:28,474 ERROR    
2018-05-07 20:44:35,592 INFO     starting application
2018-05-07 20:44:36,341 INFO     GUI load complete
2018-05-07 20:44:38,529 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 27, in updateSettings
    palette.setColor(QtCore.Qt.BackgroundRole, color)
TypeError: arguments did not match any overloaded call:
  setColor(self, QPalette.ColorGroup, QPalette.ColorRole, QColor): argument 1 has unexpected type 'ItemDataRole'
  setColor(self, QPalette.ColorRole, QColor): argument 1 has unexpected type 'ItemDataRole'

2018-05-07 20:44:38,530 ERROR    uncaught exception
2018-05-07 20:44:38,530 ERROR    
2018-05-07 20:45:01,825 INFO     starting application
2018-05-07 20:45:02,493 INFO     GUI load complete
2018-05-07 20:45:03,944 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 28, in updateSettings
    palette.setColor(QtCore.Qt.BackgroundColorRole, color)
TypeError: arguments did not match any overloaded call:
  setColor(self, QPalette.ColorGroup, QPalette.ColorRole, QColor): argument 1 has unexpected type 'ItemDataRole'
  setColor(self, QPalette.ColorRole, QColor): argument 1 has unexpected type 'ItemDataRole'

2018-05-07 20:45:03,947 ERROR    uncaught exception
2018-05-07 20:45:03,947 ERROR    
2018-05-07 20:45:11,997 INFO     starting application
2018-05-07 20:45:12,660 INFO     GUI load complete
2018-05-07 20:45:15,138 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 27, in updateSettings
    palette.setColor(QtCore.Qt.BackgroundRole, color)
TypeError: arguments did not match any overloaded call:
  setColor(self, QPalette.ColorGroup, QPalette.ColorRole, QColor): argument 1 has unexpected type 'ItemDataRole'
  setColor(self, QPalette.ColorRole, QColor): argument 1 has unexpected type 'ItemDataRole'

2018-05-07 20:45:15,141 ERROR    uncaught exception
2018-05-07 20:45:15,141 ERROR    
2018-05-07 20:45:45,996 INFO     starting application
2018-05-07 20:45:46,730 INFO     GUI load complete
2018-05-07 20:50:04,170 INFO     starting application
2018-05-07 20:50:04,940 INFO     GUI load complete
2018-05-07 20:50:07,039 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 35, in updateSettings
    dialog = SingleChannelSettingsConfig(channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 14, in __init__
    self.pushButtonColor.cliecked.connect(self.changeColor)
AttributeError: 'QPushButton' object has no attribute 'cliecked'

2018-05-07 20:50:07,040 ERROR    uncaught exception
2018-05-07 20:50:07,042 ERROR    
2018-05-07 20:50:16,140 INFO     starting application
2018-05-07 20:50:16,963 INFO     GUI load complete
2018-05-07 20:51:14,812 INFO     starting application
2018-05-07 20:51:15,526 INFO     GUI load complete
2018-05-07 20:52:55,969 INFO     starting application
2018-05-07 20:52:56,634 INFO     GUI load complete
2018-05-07 20:58:25,391 INFO     starting application
2018-05-07 20:58:26,076 INFO     GUI load complete
2018-05-07 20:59:22,717 INFO     starting application
2018-05-07 20:59:23,437 INFO     GUI load complete
2018-05-07 21:00:56,092 INFO     starting application
2018-05-07 21:00:56,713 INFO     GUI load complete
2018-05-07 21:00:58,733 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 41, in updateSettings
    dialog = SingleChannelSettingsConfig(channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 19, in __init__
    self.formLayout.addWidget(self.colorPickerButton, 2, 1)
TypeError: addWidget(self, QWidget): too many arguments

2018-05-07 21:00:58,734 ERROR    uncaught exception
2018-05-07 21:00:58,736 ERROR    
2018-05-07 21:01:43,517 INFO     starting application
2018-05-07 21:01:44,181 INFO     GUI load complete
2018-05-07 21:01:46,069 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 41, in updateSettings
    dialog = SingleChannelSettingsConfig(channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 18, in __init__
    self.formLayout.removeRow(2)
AttributeError: 'QFormLayout' object has no attribute 'removeRow'

2018-05-07 21:01:46,072 ERROR    uncaught exception
2018-05-07 21:01:46,072 ERROR    
2018-05-07 21:04:40,655 INFO     starting application
2018-05-07 21:04:41,259 INFO     GUI load complete
2018-05-08 19:12:26,976 INFO     starting application
2018-05-08 19:12:30,548 INFO     GUI load complete
2018-05-08 19:16:48,282 INFO     starting application
2018-05-08 19:16:48,907 INFO     GUI load complete
2018-05-08 19:16:55,247 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:16:55,250 ERROR    uncaught exception
2018-05-08 19:16:55,253 ERROR    
2018-05-08 19:16:55,253 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:16:55,255 ERROR    uncaught exception
2018-05-08 19:16:55,255 ERROR    
2018-05-08 19:17:21,295 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:21,296 ERROR    uncaught exception
2018-05-08 19:17:21,296 ERROR    
2018-05-08 19:17:21,296 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:21,296 ERROR    uncaught exception
2018-05-08 19:17:21,296 ERROR    
2018-05-08 19:17:27,773 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:27,775 ERROR    uncaught exception
2018-05-08 19:17:27,775 ERROR    
2018-05-08 19:17:27,775 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:27,776 ERROR    uncaught exception
2018-05-08 19:17:27,776 ERROR    
2018-05-08 19:17:38,589 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:38,591 ERROR    uncaught exception
2018-05-08 19:17:38,591 ERROR    
2018-05-08 19:17:38,592 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:38,592 ERROR    uncaught exception
2018-05-08 19:17:38,592 ERROR    
2018-05-08 19:17:38,625 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\idCheckBox.py", line 164, in changeChannelConfig
    SingleChannelSettingsConfig.updateSettings(self.channel)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\singleChannelSettingsConfig.py", line 51, in updateSettings
    channel.displayScaleFactor = float(dialog.lineEditScaleFactor.text())
ValueError: invalid literal for float(): 0,5

2018-05-08 19:17:38,625 ERROR    uncaught exception
2018-05-08 19:17:38,625 ERROR    
2018-05-08 19:17:45,326 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:45,328 ERROR    uncaught exception
2018-05-08 19:17:45,328 ERROR    
2018-05-08 19:17:45,328 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:45,329 ERROR    uncaught exception
2018-05-08 19:17:45,331 ERROR    
2018-05-08 19:17:55,877 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:55,878 ERROR    uncaught exception
2018-05-08 19:17:55,878 ERROR    
2018-05-08 19:17:55,878 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:17:55,880 ERROR    uncaught exception
2018-05-08 19:17:55,880 ERROR    
2018-05-08 19:18:09,661 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:18:09,663 ERROR    uncaught exception
2018-05-08 19:18:09,663 ERROR    
2018-05-08 19:18:09,663 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:18:09,664 ERROR    uncaught exception
2018-05-08 19:18:09,664 ERROR    
2018-05-08 19:18:29,269 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:18:29,270 ERROR    uncaught exception
2018-05-08 19:18:29,270 ERROR    
2018-05-08 19:18:29,272 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:18:29,273 ERROR    uncaught exception
2018-05-08 19:18:29,273 ERROR    
2018-05-08 19:19:13,072 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:13,072 ERROR    uncaught exception
2018-05-08 19:19:13,072 ERROR    
2018-05-08 19:19:13,073 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:13,075 ERROR    uncaught exception
2018-05-08 19:19:13,075 ERROR    
2018-05-08 19:19:18,006 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:18,009 ERROR    uncaught exception
2018-05-08 19:19:18,009 ERROR    
2018-05-08 19:19:18,009 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:18,010 ERROR    uncaught exception
2018-05-08 19:19:18,010 ERROR    
2018-05-08 19:19:28,622 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:28,625 ERROR    uncaught exception
2018-05-08 19:19:28,625 ERROR    
2018-05-08 19:19:28,625 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:28,627 ERROR    uncaught exception
2018-05-08 19:19:28,627 ERROR    
2018-05-08 19:19:40,924 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:40,926 ERROR    uncaught exception
2018-05-08 19:19:40,927 ERROR    
2018-05-08 19:19:40,927 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:40,928 ERROR    uncaught exception
2018-05-08 19:19:40,928 ERROR    
2018-05-08 19:19:50,089 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:50,091 ERROR    uncaught exception
2018-05-08 19:19:50,091 ERROR    
2018-05-08 19:19:50,091 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:19:50,092 ERROR    uncaught exception
2018-05-08 19:19:50,092 ERROR    
2018-05-08 19:20:04,815 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:20:04,818 ERROR    uncaught exception
2018-05-08 19:20:04,818 ERROR    
2018-05-08 19:20:04,818 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:20:04,821 ERROR    uncaught exception
2018-05-08 19:20:04,822 ERROR    
2018-05-08 19:55:13,019 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 687, in save
    self.projectConfigManager.save(self.projectSettings, self.channels, self.commands)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 90, in save
    f.write(json.dumps(everythingDict, indent=4))
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\Python27\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Python27\lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: PyQt4.QtCore.QString(u'') is not JSON serializable

2018-05-08 19:55:13,022 ERROR    uncaught exception
2018-05-08 19:55:13,022 ERROR    
2018-05-08 19:55:17,983 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 624, in openRecent
    self.loadProject(recentPath)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 632, in loadProject
    self.projectSettings, self.channels, self.commands, self.messageFormatList, self.communicator = self.projectConfigManager.buildModelFromConfigFile(pathToProjectFile)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 113, in buildModelFromConfigFile
    jsonStuff = self.open(pathToConfigFile)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 98, in open
    return json.loads(content)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2018-05-08 19:55:17,983 ERROR    uncaught exception
2018-05-08 19:55:17,983 ERROR    
2018-05-08 19:55:24,158 CRITICAL uncaught exception:

Traceback (most recent call last):
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 624, in openRecent
    self.loadProject(recentPath)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\gui\mainWindow.py", line 632, in loadProject
    self.projectSettings, self.channels, self.commands, self.messageFormatList, self.communicator = self.projectConfigManager.buildModelFromConfigFile(pathToProjectFile)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 113, in buildModelFromConfigFile
    jsonStuff = self.open(pathToConfigFile)
  File "D:\00 eigene Daten\000 FH\S 4\Regelungstechnik\Regelungsversuch\microRay\core\configFileManager.py", line 98, in open
    return json.loads(content)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2018-05-08 19:55:24,158 ERROR    uncaught exception
2018-05-08 19:55:24,160 ERROR    
2018-05-08 19:57:56,589 INFO     starting application
2018-05-08 19:57:57,390 INFO     GUI load complete
2018-05-08 19:59:28,687 INFO     starting application
2018-05-08 19:59:29,341 INFO     GUI load complete
2018-05-08 19:59:37,437 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:59:37,440 ERROR    uncaught exception
2018-05-08 19:59:37,443 ERROR    
2018-05-08 19:59:37,444 CRITICAL uncaught exception:

TypeError: updateCurve() takes exactly 3 arguments (2 given)

2018-05-08 19:59:37,444 ERROR    uncaught exception
2018-05-08 19:59:37,444 ERROR    
